/*
 * File: app/view/ui/MyContainer.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.MyContainer', {
    extend: 'Ext.Panel',

    config: {
        id: 'mycontainer',
        showAnimation: 'slideIn',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                id: 'mylist',
                itemId: 'mylist',
                itemTpl: [
                    '<div style="float: left; width: 80%;">{name}</div>',
                    '<div style="float: left; width: 20%; text-align: right; color: darkblue; font-weight: bold">{distance} m</div>',
                    '<tpl for="departures">',
                    '<div>',
                    '	<div style="color: white; background-color: {color]}; width: 15%; text-align: center; padding: 5px; border-radius: 10px 10px 10px 10px; float: left;">{line}</div>',
                    '	<div style="float: left; width: 70%; text-align: left; padding: 5px;">{destination}</div>',
                    '	<tpl if="predictedTime!=null">',
                    '	<div style="font-style: italic; float: left; width: 15%; text-align: right; padding: 5px;">{predictedTime}m</div>',
                    '	</tpl>',
                    '	<tpl if="plannedTime!=null">',
                    '	<div style="float: left; width: 15%; text-align: right; padding: 5px;">{plannedTime}m</div>',
                    '	</tpl>',
                    ' 	<div id="footer" style="clear: both; height: 3px;"></div>',
                    '</div>',
                    '</tpl>'
                ],
                store: 'MyJsonStore'
            },
            {
                xtype: 'button',
                docked: 'bottom',
                id: 'mybutton',
                itemId: 'mybutton',
                ui: 'action',
                text: 'Refresh'
            }
        ]
    }

});