/*
 * File: app/view/ui/TitleContainer.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.TitleContainer', {
    extend: 'Ext.Container',

    config: {
        html: '<img style = "display: block; margin-left: auto; margin-right: auto" alt="" src="data/Haltestelle2.png"> </div> <div style="font-family: \'Alfa Slab One\',Arial; color: #224567; font-size: 2em;     line-height: 100%;     margin: 0;     text-align: center;     text-shadow: 0 0 2px #333333; font-weight: normal;text-transform: lowercase;">thinking...</div>',
        id: 'titlecontainer',
        layout: {
            type: 'fit'
        }
    }

});