/*
 * File: app/store/base/MyStore.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Designer does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.base.MyStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.MyModel2'
    ],

    config: {
        data: [
            {
                firstName: 'Ed',
                lastName: 'Spencer'
            },
            {
                firstName: 'Tommy',
                lastName: 'Maintz'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Aaron',
                lastName: 'Conran'
            },
            {
                firstName: 'Jamie',
                lastName: 'Avins'
            }
        ],
        model: 'MyApp.model.MyModel2',
        storeId: 'MyStore'
    }
});